# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/user/-1
Content-Type: application/json

{
  "token": "-2042923725"
}

###

PUT http://localhost:8080/user/0
Content-Type: application/json

{
  "token": "-253989935",
  "user": {
    "id": 0,
    "role": "ADMIN",
    "username": "string",
    "firstName": "test",
    "lastName": "superTest",
    "email": "test",
    "password": "test",
    "phone": "test"
  }
}

###

DELETE http://localhost:8080/user/0
Content-Type: application/json

{
  "token": "-2065177793",
  "requestUserRole": "MODERATOR"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "user": {
    "id": 0,
    "login": "string",
    "password": "string"
  }
}

###

POST http://localhost:8080/user/logout
Content-Type: application/json

{
  "token": "-1048067328"
}

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "role": "ADMIN",
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "login": "string",
  "password": "string",
  "phone": "string"
}

###